services:
    - type: web
      name: minijira
      runtime: node
      buildCommand: npm install && npm run build && npm run db:init
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
      disk:
          name: minijira-data
          mountPath: /opt/render/project/src/server/db
          sizeGB: 1
